apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-storefront-api
  namespace: retail
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - storefront.ecommerce.io
    secretName: storefront-tls
  rules:
  - host: storefront.ecommerce.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: storefront-api
            port:
              number: 80